### ISSUE TITLE
Big Sur引导卡进系统登录前的代码界面，HDMI插拔死机

### ISSUE THREAD

**Issue by hongxuanzheng** [k900601j/Dell-Inspiron-15-7559-hackintosh-opencore#1]
你好，我尝试用了您的引导文件进行Big  Sur的引导，开机能正常跑代码，到快进系统登录页面之前卡住不动，按动音量快捷键有声音，说明系统正常引导，但是画面定在代码界面，尝试换了我的显卡注入参数后能进系统但是HDMI无法正常使用，插入HDMI马上就死机重启，我的显卡也是hd530，i7-6700HQ的cpu

**Comment by k900601j** [comment]
Hello? I just saw it.
If you want to use hdmi, you need to replace the current setting of smbios
MacBook Pro 13.3 with 13.1.
The hdmi needs to connect the cable after osx boots completely. It does not
work from boot time.
I hope it will be solved well.

2021년 1월 25일 (월) 오후 2:52, hongxuanzheng <notifications@github.com>님이 작성:

**Comment by hongxuanzheng** [comment]
@k900601j 非常感谢您的指导，我在使用您的hd530的设备属性注入后为什么无法进系统呢

**Comment by hongxuanzheng** [comment]
@k900601j 非常感谢您的回复，但是为什么使用您的显卡设备属性注入就会无法进入系统登录界面，删除就可以进入？

**Comment by k900601j** [comment]
[config.plist fixed graphic.zip](https://github.com/k900601j/Dell-Inspiron-15-7559/files/5871551/config.plist.fixed.graphic.zip)

  Would you like to try booting with the attached config? Even if you don't hold the pci devices, it's gonna boot up.
You can use it well through kext, but if you catch it wrong, it doesn't even boot up. 
  I set up pci devices using hackintool, but the video value extracted from hackintool was not even booted. 
So I also thought about it like you and referred to other people's things to see if they were applied well. I hope it goes well. Can I get some feedback?

**Comment by hongxuanzheng** [comment]
@k900601j 非常感谢您为我提供修复显卡的config文件，但是我根据您原来的config修改机型为11,2并且删除显卡属性之后HDMI输出成功修复，其他功能一切正常，所以HDMI已经成功修复！非常感谢！

**Comment by hongxuanzheng** [comment]
非常抱歉这么久才回复你，由于最近工作和家庭比较繁忙，所以没能及时调整EFI文件及时回复您 @k900601j

**Comment by hongxuanzheng** [comment]
@k900601j 目前存在的问题是声卡麦克风无输入，Windows 10下也声卡也没有麦克风输入，声音输出一切正常！这个是什么问题呢，我尝试换了好多id都是一样的问题！

**Comment by hongxuanzheng** [comment]
兄弟，能不能帮忙做一个Monterey的EFI @k900601j
